services:
  db:
    image: mysql:5.7.30
    volumes:
       - ./mysql_data:/var/lib/mysql
    ports:
      - "3388:3306"
    restart: "no"
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: ilovebooks
      MYSQL_ROOT_PASSWORD: AY7r83bTsfFLmXVx
    networks:
      - mydb
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: AY7r83bTsfFLmXVx
    networks:
      - mydb
networks:
    mydb: